"title"
"Anaconda Confessions"
"Deliverance Mulholland"
"Encino Elf"
"Factory Dragon"
"Gandhi Kwai"
"Newton Labyrinth"
"Notorious Reunion"
"Papi Necklace"
"Roxanne Rebel"
"Sun Confessions"
"Talented Homicide"
"Theory Mermaid"
"Valentine Vanishing"
"Wait Cider"
"Young Language"
